#!/bin/bash

echo "$(pwd)"

if {
  [[ "$(type framework 2>&1)" =~ "non trouvé" ]] ||
  [[ "$(type framework 2>&1)" =~ "not found" ]] ||
  [[ ! -f "$(pwd)/bash-aliases-framework" ]]
};then
  git clone git@github.com:nicolachoquet06250/bash-aliases-framework.git
fi

if [[ ! -d "${HOME}/.oh-my-posh-installer" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/oh-my-posh-installer"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.oh-my-posh-installer";
fi

file_path=".oh-my-posh-installer/.bash_aliases_oh-my-posh"

source_1="source \"\${HOME}/${file_path}\""
source_2="source \"~/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"
bash_aliases_content="$(cat "${bash_aliases_path}")"

if {
  [[ ! "${bash_aliases_content}" =~ $source_1 ]] &&
  [[ ! "${bash_aliases_content}" =~ $source_2 ]]
};then
  echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}"
fi