#!/bin/bash

if [[ ! -d "${HOME}/.oh-my-posh-installer" ]];then
  ln -s "$(pwd)" "${HOME}/.oh-my-posh-installer";
fi

source_1="source \"\${HOME}/.oh-my-posh-installer/.bash_aliases_oh-my-posh\""
source_2="source \"~/.oh-my-posh-installer/.bash_aliases_oh-my-posh\""

if {
  [[ ! "$(cat "${HOME}/.bash_aliases")" =~ $source_1 ]] &&
  [[ ! "$(cat "${HOME}/.bash_aliases")" =~ $source_2 ]]
};then
  echo "source \"\${HOME}/.oh-my-posh-installer/.bash_aliases_oh-my-posh\"" >> "${HOME}/.bash_aliases"
fi